change build github actions to release

diff --git a/.github/workflows/dev_build.yml b/.github/workflows/dev_build.yml
--- a/.github/workflows/dev_build.yml
+++ b/.github/workflows/dev_build.yml
@@ -53,7 +53,7 @@ jobs:
       - name: Build Debug APK
         env:
           API_URL: ${{ secrets.API_URL }}
-        run: ./gradlew assembleDebug -PAPI_URL=$API_URL
+        run: ./gradlew assembleRelease -PAPI_URL=$API_URL
 
 
       # Calculate end time before sending to Telegram
@@ -70,7 +70,13 @@ jobs:
           TAG_NAME: ${{ github.ref_name }}
           ELAPSED: ${{ env.ELAPSED }}
         run: |
+          APK_PATH=$(ls app/build/outputs/apk/release/*.apk | head -n 1)
+          if [ ! -f "$APK_PATH" ]; then
+          echo "❌ Release APK not found!"
+          exit 1
+          fi
+          
           curl -F chat_id=${{ secrets.CHAT_ID }} \
-               -F document=@app/build/outputs/apk/debug/app-debug.apk \
+               -F document=@"$APK_PATH" \
                -F caption="APK Build for tag: $TAG_NAME\n⏱ Total build time: $ELAPSED seconds" \
                "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendDocument"
